Repository denizdikbiyik/SWE574Project, pull requests merged in 2022-05, with the labels that each got.

#251 [BUG] Wikidata search error when entered more than one word as keywor…
  wiki/templates/wiki/wiki_description.html
  wiki/tests.py
  wiki/views.py
Labels: bug

#253 Enhance Admin Service List Filters #252
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_service_list/views.py
Labels: bug, enhancement, frontend, Effort (Difficult), fixed

#254 Event application migration
  social/migrations/0006_auto_20220501_1802.py
Labels: database

#256 Enhance Admin Event List Filters #255
  dashboard_event_list/templates/dashboard_event_list/eventlist.html
  dashboard_event_list/views.py
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_service_list/views.py
Labels: bug, enhancement, frontend, backend, Effort (Medium)

#260 Bug in Search for Turkish Characters #191
  social/views.py
Labels: backend, Effort (Medium), fixed

#261 Bug in Search for Turkish Characters #191
  social/views.py
Labels: bug, fixed

#263 Bug in name sorting #262
  dashboard_event_list/views.py
  dashboard_service_list/views.py
Labels: bug, fixed

#264 bugsolved
  dashboard_user_list/templates/dashboard_user_list/userlist.html
  dashboard_user_list/views.py
Labels: frontend

#267 Timeline updated and dashboard edited with changes #207 #225 #226
  media/events_chart.png
  media/events_month_chart.png
  media/handshaken_month_services_chart.png
  media/handshaken_services_chart.png
  media/operations_month_chart.png
  media/services_chart.png
  media/services_month_chart.png
  media/uploads/profile_pictures/jillbass.jpeg
  media/users_chart.png
  media/users_month_chart.png
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/admindashboardindex.html
  social/templates/social/timeline.html
  social/views.py
Labels: frontend, backend, Effort (Difficult)

#268 Search logs, hint, wordcloud #228 #230 #231
  CommUnitySocial/__pycache__/settings.cpython-310.pyc
  CommUnitySocial/settings.py
  landing/templates/landing/navbar.html
  media/events_chart.png
  media/handshaken_services_chart.png
  media/operations_month_chart.png
  media/searchlogwordcloud.png
  media/services_chart.png
  media/services_month_chart.png
  requirements.txt
  social/__pycache__/admin.cpython-310.pyc
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/admin.py
  social/migrations/0008_search.py
  social/migrations/0009_search_searchtype.py
  social/models.py
  social/templates/social/searchloglist.html
  social/templates/social/searchloglistzero.html
  social/templates/social/searchlogwordcloud.html
  social/urls.py
  social/views.py
Labels: frontend, backend, Effort (Difficult)

#270 [BUG] Smart sorting crash #269 Note: Crash is fixed.
  social/views.py
Labels: bug

#272 Combine Filter and Search Buttons on All Services Page #198
  landing/templates/landing/navbar.html
  social/templates/social/service-search.html
  social/views.py
Labels: enhancement, frontend, database, backend, Effort (Difficult)

#273 Sort Services #257
  social/templates/social/service-search.html
  social/views.py
Labels: frontend, backend, Effort (Medium)

#295 Deactivated Typo #294
  CommUnitySocial/__pycache__/settings.cpython-310.pyc
  media/events_chart.png
  media/handshaken_services_chart.png
  media/searchlogwordcloud.png
  media/services_chart.png
  social/__pycache__/admin.cpython-310.pyc
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/dashboard_event_detail.html
  social/templates/social/dashboard_service_detail.html
  social/templates/social/dashboard_user_detail.html
Labels: frontend, Effort (Easy)

#296 Nav buttons and admin dropdown #277 #282
  landing/templates/landing/navbar.html
Labels: frontend, Effort (Easy)

#297 Complainted text is corrected #281
  social/views.py
Labels: frontend, Effort (Easy)

#298 Index page corrections #283
  landing/templates/landing/index.html
  social/__pycache__/views.cpython-310.pyc
Labels: frontend, Effort (Easy)

#299 Featured Time Shown #288 #289
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/featuredevents.html
  social/templates/social/featuredservices.html
  social/views.py
Labels: frontend, backend, Effort (Medium)

#300 Online chart renamed #290
  media/users_chart.png
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: frontend, Effort (Easy)

#301 Back button added to dashboard #278
  dashboard_event_list/templates/dashboard_event_list/eventlist.html
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_user_list/templates/dashboard_user_list/userlist.html
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/complaints.html
  social/templates/social/deactivateds.html
  social/templates/social/featuredevents.html
  social/templates/social/featuredservices.html
Labels: frontend, Effort (Easy)

#302 Wordcloud error for texts solved #271
  media/searchlogwordcloud.png
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/searchlogwordcloud.html
  social/views.py
Labels: backend, Effort (Difficult)

#303 Space and borders removed #293 #284
  landing/templates/landing/index.html
  media/operations_month_chart.png
  media/searchlogwordcloud.png
  media/services_chart.png
  media/services_month_chart.png
  media/uploads/service_pictures/beancooking_76sI1nx.jpeg
  media/uploads/service_pictures/beancooking_lhtlif9.jpeg
  media/uploads/service_pictures/finance_a8HlpMd.jpeg
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/allevents.html
  social/templates/social/allservices.html
  social/templates/social/allusers.html
  social/templates/social/application_delete.html
  social/templates/social/application_edit.html
  social/templates/social/appliedevents.html
  social/templates/social/appliedservices.html
  social/templates/social/complaint-delete.html
  social/templates/social/complaint-edit.html
  social/templates/social/complaint.html
  social/templates/social/complaints.html
  social/templates/social/createdevents.html
  social/templates/social/createdrequests.html
  social/templates/social/createdservices.html
  social/templates/social/dashboard_event_detail.html
  social/templates/social/dashboard_service_detail.html
  social/templates/social/dashboard_user_detail.html
  social/templates/social/deactivateds.html
  social/templates/social/event-application_delete.html
  social/templates/social/event-search.html
  social/templates/social/event_communication_delete.html
  social/templates/social/event_delete.html
  social/templates/social/event_detail.html
  social/templates/social/event_like_list.html
  social/templates/social/featuredevents.html
  social/templates/social/featuredservices.html
  social/templates/social/followers_list.html
  social/templates/social/followings_list.html
  social/templates/social/mycomplaints.html
  social/templates/social/mylikes.html
  social/templates/social/notifications.html
  social/templates/social/onlineusers.html
  social/templates/social/profile.html
  social/templates/social/profile_edit.html
  social/templates/social/rating-delete.html
  social/templates/social/rating-edit.html
  social/templates/social/rating.html
  social/templates/social/request_create.html
  social/templates/social/request_delete.html
  social/templates/social/request_detail.html
  social/templates/social/requestsfromme.html
  social/templates/social/service-filter.html
  social/templates/social/service-search.html
  social/templates/social/service_communication_delete.html
  social/templates/social/service_delete.html
  social/templates/social/service_detail.html
  social/templates/social/service_like_list.html
  social/templates/social/timeline.html
  social/templates/social/usersevents.html
  social/templates/social/usersservices.html
Labels: frontend, Effort (Medium)

#304 city search added #213 #214 #215 #216
  social/forms.py
  social/migrations/0010_service_location_name.py
  social/migrations/0011_auto_20220507_1842.py
  social/migrations/0012_auto_20220507_1849.py
  social/migrations/0013_event_city.py
  social/models.py
Labels: database, backend, Effort (Difficult)

#307 Complaint date added #292
  media/operations_month_chart.png
  media/services_chart.png
  media/services_month_chart.png
  media/users_chart.png
  social/templates/social/complaints.html
Labels: frontend, backend, Effort (Medium)

#308 Complaint order
  media/services_chart.png
  media/users_chart.png
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: frontend, backend, Effort (Easy)

#309 Notification changes are done #285
  media/handshaken_month_services_chart.png
  media/handshaken_services_chart.png
  media/operations_month_chart.png
  media/services_chart.png
  media/services_month_chart.png
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/notifications.html
  social/views.py
Labels: frontend, backend, Effort (Medium)

#310 Deactivated users are redirected #265
  dashboard_event_list/views.py
  dashboard_service_list/views.py
  dashboard_user_list/views.py
  landing/templates/landing/index.html
  media/events_chart.png
  media/handshaken_services_chart.png
  media/operations_month_chart.png
  media/services_chart.png
  media/users_chart.png
  media/users_month_chart.png
  social/__pycache__/views.cpython-310.pyc
  social/tests/__pycache__/test_views.cpython-310.pyc
  social/views.py
  wiki/tests.py
  wiki/views.py
Labels: backend, Effort (Difficult)

#311 Date added to timeline #276
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/timeline.html
Labels: frontend, Effort (Easy)

#313 redirect to wiki
  wiki/views.py
Labels: backend, Effort (Easy)

#314 Services Page Default Category #306
  social/views.py
Labels: bug, Effort (Easy), fixed

#316 Edit Address for Service #274
  social/views.py
Labels: bug, Effort (Easy)

#318 Edit Address for Event #275
  social/views.py
Labels: bug, Effort (Easy), fixed

#319 [BUG] Other Profile Interest Add Remove Buttons #315
  social/templates/social/profile.html
Labels: bug

#320 Pagination to All Services Page #196
  social/templates/social/service-search.html
  social/views.py
Labels: frontend, backend, Effort (Medium)

#336 Admin Dashboard Sub Pages Back Button Rename #328
  dashboard_event_list/templates/dashboard_event_list/eventlist.html
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_user_list/templates/dashboard_user_list/userlist.html
  media/events_chart.png
  media/handshaken_month_services_chart.png
  media/handshaken_services_chart.png
  media/operations_month_chart.png
  media/searchlogwordcloud.png
  media/services_chart.png
  media/services_month_chart.png
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/complaints.html
  social/templates/social/deactivateds.html
  social/templates/social/featuredevents.html
  social/templates/social/featuredservices.html
  social/templates/social/onlineusers.html
Labels: frontend, Effort (Easy)

#337 Log Text Changes (Do for Timeline and Notification if needed) #326
  dashboard_event_list/templates/dashboard_event_list/eventlist.html
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_user_list/templates/dashboard_user_list/userlist.html
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: frontend, Effort (Easy)

#338 Location and Search - Sort Related Improvements
  social/forms.py
  social/templates/social/service-search.html
  social/views.py
Labels: frontend, backend, Effort (Difficult)

#343 Search Log Visibility #280
  landing/templates/landing/navbar.html
  media/searchlogwordcloud.png
  social/templates/social/searchloglist.html
  social/templates/social/searchloglistzero.html
  social/templates/social/searchlogwordcloud.html
  social/templates/social/service_create.html
Labels: frontend, backend, Effort (Medium)

#344 Timeline UI Changes #325
  media/uploads/service_pictures/beancooking_4BiSKrK.jpeg
  social/__pycache__/forms.cpython-310.pyc
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/timeline.html
Labels: frontend, Effort (Medium)

#349 Separate Search Bar for Location in Adm Service Page #348
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_service_list/views.py
Labels: enhancement, frontend, backend, Effort (Medium)

#351 Separate Search Bar for Location in Adm Event Page #350
  dashboard_event_list/templates/dashboard_event_list/eventlist.html
  dashboard_event_list/views.py
Labels: frontend, backend, Effort (Medium)

#352 Pagination to All Users Page #322
  social/templates/social/allusers.html
  social/views.py
Labels: frontend, Effort (Medium)

#355 Recommendation Error for Anonymous Users #353
  landing/__pycache__/views.cpython-310.pyc
  landing/views.py
  media/searchlogwordcloud.png
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend

#360 color change on navbar
  landing/templates/landing/navbar.html
Labels: frontend, Effort (Easy)

#362 Pagination to All Services Page #196 with map search
  social/templates/social/map.html
  social/templates/social/service-search.html
  social/urls.py
  social/views.py
Labels: frontend, backend, Effort (Difficult)

#363 Location and Search - Sort Related Improvements #332
  landing/templates/landing/navbar.html
  social/templates/social/event-search.html
  social/templates/social/map.html
  social/templates/social/service-search.html
  social/views.py
Labels: frontend, backend, Effort (Difficult)

#365 Smart Search and Pagination Combining Error #356
  social/views.py
Labels: bug

#367 Filter Dropdown Only Actives for Events #287
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_service_list/views.py
Labels: enhancement, frontend, backend, Effort (Medium)

#368 Filter Dropdown Only Actives for Events #287
  dashboard_event_list/templates/dashboard_event_list/eventlist.html
  dashboard_event_list/views.py
Labels: enhancement, frontend, backend, Effort (Easy)

#370 Key Error Bug in Services Page #369
  social/views.py
Labels: bug

#372 Decoration and text changes
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/event-search.html
  social/templates/social/service-search.html
  social/templates/social/service_edit.html
Labels: frontend, Effort (Easy)

#373 Retrieve Wikidata description while editing an Event #190
  social/templates/social/event_edit.html
  social/views.py
  wiki/templates/wiki/wiki_event_desc_edit.html
  wiki/urls.py
  wiki/views.py
Labels: frontend, backend, Effort (Medium)

#374 Change Recommendation Menu Color #357
  landing/templates/landing/navbar.html
Labels: frontend, Effort (Easy)

#376 Pagination 10 for ALL Pages #321
  dashboard_event_list/views.py
  dashboard_service_list/views.py
Labels: frontend, Effort (Easy)

#377 Date Passed Services Credit Back for Creator #375
  landing/__pycache__/views.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend, Effort (Difficult)

#378 Pandas removed
  CommUnitySocial/__pycache__/settings.cpython-310.pyc
  CommUnitySocial/settings.py
  media/events_chart.png
  media/handshaken_month_services_chart.png
  media/handshaken_services_chart.png
  media/operations_month_chart.png
  media/searchlogwordcloud.png
  media/services_chart.png
  media/services_month_chart.png
  requirements.txt
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend, Effort (Difficult)

#382 Events page search results are not stored #380
  social/views.py
Labels: backend, Effort (Medium)

#386 Add New Tests to Admin Event List Feature #385
  dashboard_event_list/tests/test_views.py
Labels: testing, Effort (Medium)

#395 [BUG] Faker Createdata is not working on MacOS #393
  social/management/commands/createdata.py
Labels: database

#403 Bring Location Search with map to the All Events Page #402
  social/models.py
  social/templates/social/event-search.html
  social/urls.py
  social/views.py
Labels: frontend, backend, Effort (Difficult)

#411 [BUG] Location Search at Events throwing exception when no coordinate…
  social/templates/social/event-search.html
  social/views.py
Labels: frontend, backend, Effort (Medium)

#413 Bring the Map to Service Search Page #412
  social/templates/social/service-search.html
  social/views.py
Labels: frontend, backend, Effort (Medium)

#420 [BUG] - Recommendation like multiplies the recommended services #405
  social/views.py
Labels: bug

#424 Add logs to create fake service and create fake event #419
  social/management/commands/createdata.py
  social/management/commands/interest_example.xlsx
Labels: enhancement

#425 [BUG] Service search by category fails at pagination #422
  social/views.py
Labels: bug

#427 Show Address on Event Card #415
  social/templates/social/event-search.html
Labels: frontend, Effort (Easy)

#428 Show Address on Service Card #414
  social/templates/social/service-search.html
Labels: frontend, Effort (Easy)

#429 bug and search #399 #400
  dashboard_user_list/templates/dashboard_user_list/userlist.html
  dashboard_user_list/views.py
Labels: frontend, Effort (Easy)

#431 Back Button Revision on Admin Side #416
  CommUnitySocial/__pycache__/settings.cpython-310.pyc
  dashboard_event_list/templates/dashboard_event_list/eventlist.html
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_user_list/templates/dashboard_user_list/userlist.html
  landing/__pycache__/views.cpython-310.pyc
  media/events_chart.png
  media/events_month_chart.png
  media/handshaken_month_services_chart.png
  media/handshaken_services_chart.png
  media/operations_month_chart.png
  media/searchlogwordcloud.png
  media/services_chart.png
  media/services_month_chart.png
  media/users_chart.png
  media/users_month_chart.png
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
Labels: frontend, Effort (Easy)

#432 [BUG] Non-admin users can solve their own complaints instead of editing/deleting #426
  social/templates/social/complaint.html
  social/templates/social/complaintAdminSide.html
  social/templates/social/complaintsDoneByMe.html
  social/templates/social/mycomplaints.html
  social/views.py
Labels: frontend, backend, Effort (Medium)

#434 Edit Event Width Error #433
  media/uploads/event_pictures/singing.jpeg
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/event_edit.html
Labels: frontend, Effort (Easy)

#437 [BUG] Service search category selection is missing in the next pages …
  social/templates/social/service-search.html
  social/views.py
Labels: bug, frontend, backend, Effort (Medium)

#438 Make date sorting uniform for Event and Service #436
  social/templates/social/event-search.html
  social/views.py
Labels: frontend, Effort (Easy)

#443 [BUG] Fake service creation does not update reservehour and totalcred…
  social/management/commands/createdata.py
Labels: bug, enhancement

#446 [BUG] Services page initial search result is lost when navigating thr…
  social/templates/social/service-search.html
  social/views.py
Labels: bug

#448 Complaint bugs #445
  social/views.py
Labels: bug, backend, Effort (Medium)

#449 [BUG] Smart search priorities follow and rating do not work. #447
  social/views.py
Labels: bug

#452 Communication notification errors solved #450 #451
  social/views.py
Labels: bug, backend, Effort (Medium)

#456 No Services Result when Distance is not selected #455
  social/templates/social/event-search.html
  social/templates/social/service-search.html
  social/views.py
Labels: bug, backend, Effort (Medium)
