Repository denizdikbiyik/SWE574Project, pull requests merged in 2022-04, with the labels that each got.

#56 Admin Dashboard Member List #27
  dashboard_user_list/apps.py
  dashboard_user_list/forms.py
  dashboard_user_list/templates/dashboard_user_list/userlist.html
  dashboard_user_list/urls.py
  dashboard_user_list/views.py
Labels: testing, backend, Effort (Medium)

#57 userListToMenu
  CommUnitySocial/__pycache__/settings.cpython-310.pyc
  CommUnitySocial/__pycache__/urls.cpython-310.pyc
  CommUnitySocial/settings.py
  CommUnitySocial/urls.py
  landing/templates/landing/navbar.html
  social/__pycache__/admin.cpython-310.pyc
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
Labels: backend

#58 Admin Dashboard Service and Event Detail #24 #33
  social/templates/social/dashboard_event_detail.html
  social/templates/social/dashboard_service_detail.html
  social/views.py
Labels: backend

#60 Refactoring Admin Dashboard Service List Test #48
  dashboard_event_list/tests/test_views.py
  dashboard_service_list/tests/test_views.py
Labels: testing

#62 Updated dashboard
  dashboard_event_list/templates/dashboard_event_list/eventlist.html
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  landing/templates/landing/navbar.html
  social/__pycache__/admin.cpython-310.pyc
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend

#79 deletionInfo added #68
  social/__pycache__/forms.cpython-310.pyc
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/migrations/0057_auto_20220413_0013.py
  social/models.py
  social/views.py
Labels: backend

#80 Like Feature #77 #78
  landing/templates/landing/navbar.html
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/migrations/0058_like.py
  social/models.py
  social/templates/social/event_detail.html
  social/templates/social/event_like_list.html
  social/templates/social/mylikes.html
  social/templates/social/service_detail.html
  social/templates/social/service_like_list.html
  social/urls.py
  social/views.py
Labels: frontend, backend, Effort (Medium)

#83 Duplicate communication at refresh solved #69 #70
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: bug, backend

#102 application status is fixed on admin dashboard
  social/templates/social/dashboard_event_detail.html
  social/templates/social/dashboard_service_detail.html
Labels: bug

#105 Dashboard index and online users
  CommUnitySocial/__pycache__/settings.cpython-310.pyc
  CommUnitySocial/settings.py
  landing/__pycache__/views.cpython-310.pyc
  landing/templates/landing/navbar.html
  landing/views.py
  media/users_chart.png
  requirements.txt
  social/__pycache__/forms.cpython-310.pyc
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/admindashboardindex.html
  social/templates/social/event_detail_communication.html
  social/templates/social/onlineusers.html
  social/templates/social/service_detail_communication.html
  social/urls.py
  social/views.py
Labels: frontend, backend, Effort (Difficult)

#110 User complaints implemented and shown on admin dashboard #107 #108
  social/__pycache__/forms.cpython-310.pyc
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/forms.py
  social/migrations/0059_usercomplaints.py
  social/migrations/0060_auto_20220418_1217.py
  social/models.py
  social/templates/social/admindashboardindex.html
  social/templates/social/complaint-delete.html
  social/templates/social/complaint-edit.html
  social/templates/social/complaint.html
  social/templates/social/complaints.html
  social/templates/social/profile.html
  social/urls.py
  social/views.py
Labels: frontend, backend, Effort (Medium)

#115 Communication bugs #71 #72 #94
  media/uploads/service_pictures/ukulelechords_ONMp8Zk.jpeg
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/event_detail.html
  social/templates/social/service_detail.html
  social/views.py
Labels: bug

#117 Datetime labels edited for services and events
  landing/templates/landing/index.html
  social/templates/social/allevents.html
  social/templates/social/allservices.html
  social/templates/social/appliedevents.html
  social/templates/social/appliedservices.html
  social/templates/social/createdevents.html
  social/templates/social/createdservices.html
  social/templates/social/event-search.html
  social/templates/social/mylikes.html
  social/templates/social/service-filter.html
  social/templates/social/service-search.html
  social/templates/social/timeline.html
  social/templates/social/usersevents.html
  social/templates/social/usersservices.html
Labels: bug

#120 Add Pagination #67
  dashboard_service_list/forms.py
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_service_list/tests/test_forms.py
  dashboard_service_list/tests/test_views.py
  dashboard_service_list/views.py
Labels: enhancement, fixed

#123 Improve Complaint UI #122
  CommUnitySocial/__pycache__/settings.cpython-310.pyc
  landing/__pycache__/views.cpython-310.pyc
  social/__pycache__/forms.cpython-310.pyc
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/complaints.html
Labels: frontend, Effort (Easy)

#130 Complaint Notifications #109
  media/users_chart.png
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/notifications.html
  social/views.py
Labels: backend

#136 Deactivate objects #131
  landing/__pycache__/views.cpython-310.pyc
  landing/templates/landing/index.html
  landing/templates/landing/navbar.html
  landing/views.py
  media/uploads/service_pictures/math.png
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/migrations/0061_auto_20220420_1621.py
  social/models.py
  social/templates/social/admindashboardindex.html
  social/templates/social/event_detail.html
  social/templates/social/profile.html
  social/templates/social/service_detail.html
  social/urls.py
  social/views.py
Labels: backend, Effort (Difficult)

#138 Deactivate application #137
  media/uploads/event_pictures/eglence_Pid8jVj.png
  media/uploads/service_pictures/singing_qeFtfFq.jpeg
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/event_detail.html
  social/templates/social/service_detail.html
  social/urls.py
  social/views.py
Labels: frontend, backend, Effort (Medium)

#141 Admin Dashboard Deactivated #112
  landing/templates/landing/index.html
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/admindashboardindex.html
  social/templates/social/allevents.html
  social/templates/social/allservices.html
  social/templates/social/allusers.html
  social/templates/social/appliedevents.html
  social/templates/social/appliedservices.html
  social/templates/social/createdevents.html
  social/templates/social/createdrequests.html
  social/templates/social/createdservices.html
  social/templates/social/deactivateds.html
  social/templates/social/mylikes.html
  social/templates/social/onlineusers.html
  social/templates/social/requestsfromme.html
  social/templates/social/timeline.html
  social/templates/social/usersevents.html
  social/templates/social/usersservices.html
  social/urls.py
  social/views.py
Labels: frontend, backend, Effort (Medium)

#142 UI padding
  landing/__pycache__/views.cpython-310.pyc
  landing/templates/landing/index.html
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/event-search.html
  social/templates/social/mylikes.html
  social/templates/social/service-filter.html
  social/templates/social/service-search.html
  social/templates/social/timeline.html
Labels: frontend

#143 Numbers on Online Users Pia Chart #128
  media/users_chart.png
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: frontend, backend, Effort (Difficult)

#144 Do Not Show Datetime Passed Objects #134
  landing/__pycache__/views.cpython-310.pyc
  landing/templates/landing/index.html
  landing/views.py
  media/uploads/event_pictures/eglence_Sf7ndDH.png
  media/uploads/service_pictures/meatcooking_Dbeq03I.jpeg
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/allevents.html
  social/templates/social/allservices.html
  social/templates/social/event-search.html
  social/templates/social/service-filter.html
  social/templates/social/service-search.html
  social/templates/social/timeline.html
  social/views.py
Labels: frontend, backend, Effort (Easy)

#145 Featured #113
  media/uploads/service_pictures/beancooking_iqA2HES.jpeg
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/migrations/0062_featured.py
  social/models.py
  social/templates/social/admindashboardindex.html
  social/templates/social/event_detail.html
  social/templates/social/featuredevents.html
  social/templates/social/featuredservices.html
  social/templates/social/service_detail.html
  social/urls.py
  social/views.py
Labels: frontend, backend, Effort (Medium)

#148 Retrieve Wikidata Description for Services Created #133
  CommUnitySocial/settings.py
  CommUnitySocial/urls.py
  requirements.txt
  social/models.py
  social/templates/social/service_create.html
  social/tests/test_models.py
  social/views.py
  wiki/__init__.py
  wiki/admin.py
  wiki/apps.py
  wiki/migrations/0001_initial.py
  wiki/migrations/0002_delete_wikidescription.py
  wiki/migrations/__init__.py
  wiki/templates/wiki/wiki_description.html
  wiki/tests.py
  wiki/urls.py
  wiki/views.py
Labels: wiki, frontend, database, backend, Effort (Difficult), API

#150 test fail solved with migration
  CommUnitySocial/__pycache__/settings.cpython-310.pyc
  CommUnitySocial/__pycache__/urls.cpython-310.pyc
  landing/__pycache__/views.cpython-310.pyc
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/migrations/0063_service_wiki_description.py
  social/templates/social/service_detail.html
  social/tests/__pycache__/test_models.cpython-310.pyc
Labels: database

#152 Show Featured Services and Events #146
  landing/__pycache__/views.cpython-310.pyc
  landing/templates/landing/index.html
  landing/views.py
Labels: frontend, Effort (Easy)

#153 User Dashboard Bugs Solved #95 #96 #97 #98 #99
  dashboard_user_list/forms.py
  dashboard_user_list/templates/dashboard_user_list/userlist.html
  dashboard_user_list/views.py
Labels: bug, backend, Effort (Medium)

#158 Migration changes done 2
  landing/__pycache__/views.cpython-310.pyc
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/migrations/__pycache__/0001_initial.cpython-310.pyc
  social/migrations/__pycache__/0002_service_servicedate.cpython-310.pyc
  social/migrations/__pycache__/0003_feedback.cpython-310.pyc
  social/migrations/__pycache__/0004_auto_20211120_2243.cpython-310.pyc
  social/migrations/__pycache__/0005_userprofile.cpython-310.pyc
  social/migrations/__pycache__/0006_event.cpython-310.pyc
  social/migrations/__pycache__/0007_userprofile_followers.cpython-310.pyc
  social/migrations/__pycache__/0008_auto_20211128_1447.cpython-310.pyc
  social/migrations/__pycache__/0009_auto_20211128_1745.cpython-310.pyc
  social/migrations/__pycache__/0010_auto_20211201_1635.cpython-310.pyc
  social/migrations/__pycache__/0011_auto_20211201_2021.cpython-310.pyc
  social/migrations/__pycache__/0012_auto_20211201_2023.cpython-310.pyc
  social/migrations/__pycache__/0013_auto_20211201_2024.cpython-310.pyc
  social/migrations/__pycache__/0014_auto_20211201_2025.cpython-310.pyc
  social/migrations/__pycache__/0015_auto_20211201_2041.cpython-310.pyc
  social/migrations/__pycache__/0016_auto_20211201_2042.cpython-310.pyc
  social/migrations/__pycache__/0017_auto_20211201_2048.cpython-310.pyc
  social/migrations/__pycache__/0018_auto_20211202_2235.cpython-310.pyc
  social/migrations/__pycache__/0019_userprofile_credithour.cpython-310.pyc
  social/migrations/__pycache__/0020_auto_20211203_1818.cpython-310.pyc
  social/migrations/__pycache__/0021_auto_20211203_1824.cpython-310.pyc
  social/migrations/__pycache__/0022_auto_20211204_0434.cpython-310.pyc
  social/migrations/__pycache__/0023_userprofile_reservehour.cpython-310.pyc
  social/migrations/__pycache__/0024_auto_20211215_2012.cpython-310.pyc
  social/migrations/__pycache__/0025_auto_20211215_2108.cpython-310.pyc
  social/migrations/__pycache__/0026_remove_userprofile_userrating.cpython-310.pyc
  social/migrations/__pycache__/0027_delete_feedback.cpython-310.pyc
  social/migrations/__pycache__/0028_auto_20211224_1554.cpython-310.pyc
  social/migrations/__pycache__/0029_auto_20211225_0255.cpython-310.pyc
  social/migrations/__pycache__/0030_auto_20211225_1757.cpython-310.pyc
  social/migrations/__pycache__/0031_notifyuser.cpython-310.pyc
  social/migrations/__pycache__/0032_userprofile_unreadcount.cpython-310.pyc
  social/migrations/__pycache__/0033_auto_20211225_2332.cpython-310.pyc
  social/migrations/__pycache__/0034_eventapplication.cpython-310.pyc
  social/migrations/__pycache__/0035_auto_20211226_2131.cpython-310.pyc
  social/migrations/__pycache__/0036_auto_20211226_2148.cpython-310.pyc
  social/migrations/__pycache__/0037_tag.cpython-310.pyc
  social/migrations/__pycache__/0038_auto_20211231_0442.cpython-310.pyc
  social/migrations/__pycache__/0039_auto_20211231_0453.cpython-310.pyc
  social/migrations/__pycache__/0040_auto_20211231_1232.cpython-310.pyc
  social/migrations/__pycache__/0041_service_relatedtag.cpython-310.pyc
  social/migrations/__pycache__/0042_auto_20211231_1554.cpython-310.pyc
  social/migrations/__pycache__/0043_auto_20211231_1556.cpython-310.pyc
  social/migrations/__pycache__/0044_remove_tag_isaccepted.cpython-310.pyc
  social/migrations/__pycache__/0045_auto_20211231_1717.cpython-310.pyc
  social/migrations/__pycache__/__init__.cpython-310.pyc
Labels: database

#160 Featured limited 2 #151
  landing/templates/landing/index.html
  media/uploads/event_pictures/finance.jpeg
  media/uploads/profile_pictures/ukulele_fBexNQn.jpeg
  media/uploads/service_pictures/accounting_9XrZGQk.jpeg
  media/uploads/service_pictures/ukulelechords_XhORuz4.jpeg
  media/users_chart.png
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend

#163 Featured Duration One Week #161
  landing/__pycache__/views.cpython-310.pyc
  landing/views.py
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend, Effort (Medium)

#164 Add Location Search to Admin Service List #147
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_service_list/views.py
  social/migrations/0003_service_address.py
  social/models.py
  social/templates/social/service_detail.html
  social/tests/test_models.py
  social/views.py
Labels: frontend, database, backend, Effort (Difficult), fixed

#166 Add Location Search to Admin Event List #165
  dashboard_event_list/templates/dashboard_event_list/eventlist.html
  dashboard_event_list/views.py
  social/migrations/0004_event_event_address.py
  social/models.py
  social/templates/social/event_detail.html
  social/tests/test_models.py
  social/views.py
Labels: frontend, database, backend, Effort (Medium)

#172 Add Location Search to Events Page #170 and Add Location Search to Se…
  social/templates/social/allevents.html
  social/templates/social/allservices.html
  social/templates/social/event-search.html
  social/templates/social/service-search.html
  social/views.py
Labels: frontend, Effort (Medium)

#177 user bugs solved #95 #96 #97 #98 #99
  dashboard_user_list/templates/dashboard_user_list/userlist.html
  dashboard_user_list/views.py
Labels: bug, backend

#179 Bug and Enhancement for Admin, Services and Events Search #178
  dashboard_event_list/templates/dashboard_event_list/eventlist.html
  dashboard_event_list/views.py
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_service_list/views.py
  social/views.py
Labels: enhancement, frontend, backend, Effort (Medium), fixed

#184 Some show bugs are solved
  CommUnitySocial/__pycache__/settings.cpython-310.pyc
  landing/__pycache__/views.cpython-310.pyc
  landing/views.py
  media/uploads/service_pictures/english.jpeg
  media/uploads/service_pictures/ukulele_PmqtW2u.jpeg
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/event_detail.html
  social/templates/social/service_detail.html
  social/views.py
Labels: backend, Effort (Medium)

#185 Admin Apply #175 #176 and featured count bug solved
  media/uploads/event_pictures/english.jpeg
  media/uploads/service_pictures/finance_bKJWXBS.jpeg
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/event_detail.html
  social/templates/social/service_detail.html
  social/views.py
Labels: bug, backend, Effort (Medium)

#187 Negative value not allowed #157
  media/uploads/event_pictures/beancooking_a7H0APH.jpeg
  media/uploads/service_pictures/eglence_fUleeaT.png
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend

#188 Superadmin model
  landing/__pycache__/views.cpython-310.pyc
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/migrations/0005_userprofile_issuperadmin.py
  social/models.py
Labels: backend

#194 env file changed for db #192
  CommUnitySocial/.env
Labels: deployment, Effort (Difficult)

#199 Django admin rights removed #193
  social/__pycache__/admin.cpython-310.pyc
  social/admin.py
Labels: database

#233 Change weekly to daily featured #204
  landing/__pycache__/views.cpython-310.pyc
  landing/views.py
  media/uploads/service_pictures/beancooking_5ipSKup.jpeg
  media/uploads/service_pictures/ukulelechords_0ZZDqlE.jpeg
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend, Effort (Easy)

#234 Found word changed to yet #202
  social/templates/social/event_detail.html
  social/templates/social/service_detail.html
Labels: frontend, Effort (Easy)

#235 Send Notification When Followed #81
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend, Effort (Medium)

#236 Deactivation removed from admin own profile #205
  landing/__pycache__/views.cpython-310.pyc
  social/__pycache__/admin.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/profile.html
Labels: enhancement, backend

#237 Numbers and percentage added to online users pie #203
  media/users_chart.png
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend, Effort (Medium)

#238 Featured and Activated Notifications #206 #162
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend, Effort (Medium)

#240 Admin added and removed notifications are sent #139
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend, Effort (Medium)

#241 Super admin implemented for add remove admin #174
  social/templates/social/profile.html
Labels: frontend, backend, Effort (Easy)

#242 Dashboard status #135
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/dashboard_event_detail.html
  social/templates/social/dashboard_service_detail.html
  social/views.py
Labels: frontend, backend, Effort (Medium)

#245 Deadline added to edit and delete #208 #209 #243 #244
  social/__pycache__/views.cpython-310.pyc
  social/templates/social/event_detail.html
  social/views.py
Labels: backend, Effort (Medium)

#247 Editing limit 2 is added #210 #211
  social/__pycache__/views.cpython-310.pyc
  social/views.py
Labels: backend, Effort (Medium)

#250 Admin dashboard index text removed
  social/templates/social/admindashboardindex.html
Labels: frontend, Effort (Easy)
