Repository denizdikbiyik/SWE574Project, pull requests merged in 2022-03, with the labels that each got.

#1 Master
  README.md
Labels: project management

#29 Logging for the Operations #25
  landing/__pycache__/views.cpython-310.pyc
  landing/views.py
  media/uploads/event_pictures/accounting.jpeg
  media/uploads/event_pictures/beancooking_9KJvm8O.jpeg
  media/uploads/service_pictures/singing.jpeg
  media/uploads/service_pictures/singing_9iDqxQV.jpeg
  media/uploads/service_pictures/singing_E73RKHq.jpeg
  media/uploads/service_pictures/singing_GwHoDr6.jpeg
  media/uploads/service_pictures/singing_zkPJiWR.jpeg
  media/uploads/service_pictures/ukulele_QXoiQBj.jpeg
  media/uploads/service_pictures/ukulele_RwgnpBt.jpeg
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/migrations/0048_log.py
  social/migrations/0049_auto_20220325_0032.py
  social/migrations/0050_tag_isdeleted.py
  social/migrations/0051_auto_20220325_1031.py
  social/migrations/0052_auto_20220325_1041.py
  social/migrations/0053_remove_tag_isdeleted.py
  social/models.py
  social/views.py
Labels: project management, Effort (Difficult)

#32 Testing Logging for the Operations #25 #26
  CommUnitySocial/__pycache__/settings.cpython-310.pyc
  social/tests/__pycache__/test_views.cpython-310.pyc
  social/tests/test_views.py
Labels: testing, Effort (Medium)

#36 Admin Dashboard Service List #22
  CommUnitySocial/settings.py
  CommUnitySocial/urls.py
  dashboard_service_list/__init__.py
  dashboard_service_list/admin.py
  dashboard_service_list/apps.py
  dashboard_service_list/forms.py
  dashboard_service_list/migrations/__init__.py
  dashboard_service_list/models.py
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_service_list/tests/__init__.py
  dashboard_service_list/tests/test_forms.py
  dashboard_service_list/tests/test_urls.py
  dashboard_service_list/tests/test_views.py
  dashboard_service_list/urls.py
  dashboard_service_list/views.py
  dashboard_service_list/views_copy.py
  landing/templates/landing/navbar.html
  requirements.txt
  social/models.py
Labels: frontend, backend

#34 Admin Dashboard Service Detail #24
  social/templates/social/dashboard_service_detail.html
  social/tests/test_urls.py
  social/tests/test_views.py
  social/urls.py
  social/views.py
Labels: backend

#40 Merge Changes 1
  CommUnitySocial/__pycache__/settings.cpython-310.pyc
  CommUnitySocial/__pycache__/urls.cpython-310.pyc
  dashboard_service_list/templates/dasboard_service_list/servicelist.html
  dashboard_service_list/tests/test_views.py
  dashboard_service_list/views.py
  landing/__pycache__/views.cpython-310.pyc
  media/uploads/service_pictures/accounting_Nvl8rdf.jpeg
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/models.py
  social/tests/__pycache__/test_urls.cpython-310.pyc
  social/tests/__pycache__/test_views.cpython-310.pyc
Labels: bug, Effort (Difficult)

#41 Admin Dashboard Event Detail #33
  social/templates/social/dashboard_event_detail.html
  social/tests/test_urls.py
  social/tests/test_views.py
  social/urls.py
  social/views.py
Labels: bug

#42 Merge Corrections PR41
  social/__pycache__/models.cpython-310.pyc
  social/__pycache__/urls.cpython-310.pyc
  social/__pycache__/views.cpython-310.pyc
  social/tests/__pycache__/test_urls.cpython-310.pyc
  social/tests/__pycache__/test_views.cpython-310.pyc
  social/tests/test_views.py
Labels: bug
